In [2]:
"""feature scaling - to ccumulate all scatteed points to a particular point to get accurate model performance
types- normalization and its implementation(min max scaler)- ((Xi-min)/(max-min))(max_range-min_range)+min_range
- standarddization and implementation (z score/ standard scaler)= (Xi -x)/sd"""

'feature scaling - \ntypes- normalization and its implementation\n- standarddization and implementation'

In [4]:
#feature scaling
#Normalization
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [5]:
df=pd.read_csv("energy_dataset.csv")

In [6]:
df.head(3)

,Country,Year,Energy Type,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
0,USA,2011,Solar,85404.690027,5549.794323,5.604125e+09,1064007213,1.775278e+14,369654.644184,93087.198199,...,49.216800,57.678605,76.803228,851,75,6361,511658,25.907895,1,0
1,Australia,2008,Geothermal,22205.069382,43211.593798,6.361886e+08,1033255852,6.435372e+13,771781.636293,1752.536054,...,79.990942,1.761579,48.697825,590,39,9752,974948,95.003547,0,1
2,Canada,2013,Biomass,94102.732038,6139.117212,6.158680e+09,14895124,1.567926e+14,342707.152899,65146.592498,...,94.374040,77.657334,67.334813,101,7,311,326318,67.354539,1,0

In [7]:
df.describe() #only for numeric values

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
count,2500.000000,2500.000000,2500.000000,2.500000e+03,2.500000e+03,2.500000e+03,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000
mean,2011.437600,48743.195073,24882.910674,4.956155e+09,7.458927e+08,1.010745e+14,495701.245158,50143.392627,50800.373871,491218.412643,...,50.736720,48.442085,50.280019,496.660400,50.431200,4978.93360,502040.891200,49.749110,0.512000,0.473600
std,6.895471,28340.915147,14463.459958,2.894789e+09,4.373146e+08,5.782363e+13,291419.017957,28833.333066,28740.851763,289783.733338,...,28.623766,28.798216,28.719483,296.181011,28.877168,2881.93256,293084.636148,28.924307,0.499956,0.499402
min,2000.000000,1053.354158,114.531639,5.886994e+06,1.255357e+06,5.603965e+10,1264.851083,1036.618008,1057.783513,1124.768458,...,0.104915,0.025281,0.025733,0.000000,0.000000,3.00000,494.000000,0.033829,0.000000,0.000000
25%,2006.000000,24309.656479,12282.213159,2.473145e+09,3.720811e+08,5.049265e+13,237300.546551,25146.745295,26347.461047,242894.720511,...,26.241437,23.519814,25.934406,234.000000,26.000000,2532.00000,244438.000000,23.968451,0.000000,0.000000
50%,2011.000000,47367.117600,24689.162460,4.961772e+09,7.515190e+08,1.027006e+14,496118.165272,49706.656938,50698.800022,475721.007886,...,50.850766,48.127673,51.398964,493.000000,51.000000,4992.50000,499151.000000,50.232069,1.000000,0.000000
75%,2017.250000,73079.452832,37438.443570,7.418384e+09,1.118019e+09,1.519604e+14,753779.282813,75567.191515,75807.642495,747649.446362,...,74.908485,73.324825,74.724073,755.000000,76.000000,7465.00000,765088.000000,74.354781,1.000000,1.000000
max,2023.000000,99937.503719,49997.387577,9.998292e+09,1.499494e+09,1.999223e+14,999618.512172,99952.509817,99912.213813,999816.500175,...,99.970526,99.901347,99.998838,999.000000,99.000000,9999.00000,999226.000000,99.988355,1.000000,1.000000

In [8]:
#we have convert categorical data to  numeric or have to drop it 
scaler=MinMaxScaler()

In [9]:
df.drop(columns=["Country","Energy Type"], inplace=True)

In [10]:
df[:]=scaler.fit_transform(df)

C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.47826087 0.34782609 0.56521739 ... 0.95652174 0.         0.43478261]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)
C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.70933402 0.68880901 0.00910387 ... 0.93964665 0.5730697  0.29068513]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)
C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.75688861 0.94541604 0.58813694 ... 0.42995286 0.15828126 0.61400242]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)
C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.42284569 0.51903808 0.21442886 ... 0.13527054 0.95691383 0.61723447]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)
C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.85185185 0.59059059 0.1011011  ... 0.6026026  0.52052052 0.24524525]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)
C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.75757576 0.39393939 0.07070707 ... 0.49494949 0.46464646 0.18181818]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)
C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.63605442 0.97529012 0.03081232 ... 0.35334134 0.02460984 0.03861545]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)
C:\Users\sai\AppData\Local\Temp\ipykernel_6644\2110798244.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.51181298 0.97569118 0.32623767 ... 0.53618188 0.02085444 0.49319137]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[:]=scaler.fit_transform(df)

In [11]:
df

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
0,0.478261,0.853032,0.108961,0.560249,0.709334,0.887953,0.368997,0.930594,0.124986,0.293659,...,0.491780,0.577249,0.767982,0.851852,0.757576,0.636054,0.511813,0.258858,1,0
1,0.347826,0.213904,0.863965,0.063078,0.688809,0.321704,0.771787,0.007238,0.783336,0.826488,...,0.799935,0.017385,0.486852,0.590591,0.393939,0.975290,0.975691,0.950129,0,1
2,0.565217,0.940994,0.120775,0.615747,0.009104,0.784207,0.342005,0.648126,0.405213,0.042626,...,0.943960,0.777284,0.673272,0.101101,0.070707,0.030812,0.326238,0.673513,1,0
3,0.434783,0.887084,0.806071,0.852671,0.966182,0.675404,0.498395,0.497604,0.414273,0.840353,...,0.651261,0.450182,0.045198,0.327327,0.030303,0.770808,0.506226,0.337356,0,0
4,0.782609,0.932759,0.614257,0.508421,1.000000,0.433908,0.819148,0.627450,0.170505,0.161120,...,0.862246,0.625875,0.102642,0.985986,0.696970,0.491797,0.187708,0.595025,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,1.000000,0.394784,0.932897,0.558791,0.546403,0.555115,0.574555,0.569023,0.632558,0.790279,...,0.571310,0.489134,0.602674,0.890891,0.252525,0.999300,0.884325,0.294000,1,0
2496,0.739130,0.084956,0.569178,0.560104,0.076935,0.717182,0.741550,0.562087,0.433075,0.068099,...,0.689577,0.858808,0.392331,0.898899,0.777778,0.648359,0.447700,0.732797,1,1
2497,0.956522,0.943288,0.453923,0.859110,0.939647,0.279053,0.922889,0.853437,0.468988,0.744104,...,0.326985,0.010256,0.512698,0.602603,0.494949,0.353341,0.536182,0.251951,0,1
2498,0.000000,0.658882,0.068470,0.563919,0.573070,0.107175,0.480740,0.443783,0.741701,0.262057,...,0.602795,0.292727,0.172176,0.520521,0.464646,0.024610,0.020854,0.079625,1,0
2499,0.434783,0.121175,0.456592,0.273284,0.290685,0.650358,0.673058,0.242509,0.330313,0.667234,...,0.952564,0.173324,0.264094,0.245245,0.181818,0.038615,0.493191,0.915403,0,0

In [13]:
df.describe() #now data is consistent

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,0.497287,0.482280,0.496531,0.495403,0.497008,0.505430,0.495252,0.496450,0.503190,0.490736,...,0.506999,0.484769,0.502678,0.497158,0.509406,0.497792,0.502184,0.497379,0.512000,0.473600
std,0.299803,0.286607,0.289949,0.289699,0.291886,0.289312,0.291900,0.291493,0.290739,0.290163,...,0.286623,0.288340,0.287272,0.296477,0.291689,0.288309,0.293457,0.289375,0.499956,0.499402
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.260870,0.235187,0.243925,0.246913,0.247508,0.252352,0.236425,0.243744,0.255827,0.242087,...,0.261717,0.235237,0.259156,0.234234,0.262626,0.253001,0.244254,0.239455,0.000000,0.000000
50%,0.478261,0.468364,0.492647,0.495965,0.500764,0.513566,0.495669,0.492035,0.502163,0.475218,...,0.508141,0.481621,0.513871,0.493493,0.515152,0.499150,0.499290,0.502211,1.000000,0.000000
75%,0.750000,0.728389,0.748231,0.741813,0.745385,0.760030,0.753755,0.753474,0.756161,0.747503,...,0.749042,0.733905,0.747184,0.755756,0.767677,0.746499,0.765565,0.743548,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [17]:
 
scaler=MinMaxScaler(feature_range=(1, 10))
df[:]=scaler.fit_transform(df)
df

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
0,5.304348,8.677287,1.980645,6.042244,7.384006,8.991576,4.320976,9.375350,2.124872,3.642929,...,5.426018,6.195238,7.911834,8.666667,7.818182,6.724490,5.606317,3.329725,10,1
1,4.130435,2.925136,8.775689,1.567703,7.199281,3.895332,7.946087,1.065139,8.050021,8.438394,...,8.199418,1.156461,5.381667,6.315315,4.545455,9.777611,9.781221,9.551163,1,10
2,6.086957,9.468945,2.086972,6.541722,1.081935,8.057865,4.078048,6.833135,4.646916,1.383636,...,9.495638,7.995555,7.059447,1.909910,1.636364,1.277311,3.936139,7.061620,10,1
3,4.913043,8.983759,8.254636,8.674035,9.695641,7.078633,5.485557,5.478439,4.728454,8.563181,...,6.861347,5.051642,1.406779,3.945946,1.272727,7.937275,5.556033,4.036205,1,1
4,8.043478,9.394829,6.528309,5.575790,10.000000,4.905171,8.372333,6.647050,2.534545,2.450082,...,8.760213,6.632876,1.923780,9.873874,7.272727,5.426170,2.689372,6.355221,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,10.000000,4.553053,9.396071,6.029119,5.917629,5.996037,6.170993,6.121207,6.693025,8.112510,...,6.141786,5.402209,6.424067,9.018018,3.272727,9.993697,8.958928,3.646001,10,1
2496,7.652174,1.764607,6.122601,6.040933,1.692418,7.454637,7.673952,6.058784,4.897675,1.612887,...,7.206190,8.729275,4.530975,9.090090,8.000000,6.835234,5.029297,7.595171,10,10
2497,9.608696,9.489592,5.085305,8.731988,9.456820,3.511474,9.305997,8.680933,5.220892,7.696935,...,3.942861,1.092300,5.614284,6.423423,5.454545,4.180072,5.825637,3.267561,1,10
2498,1.000000,6.929935,1.616229,6.075270,6.157627,1.964574,5.326660,4.994048,7.675311,3.358514,...,6.425156,3.634544,2.549587,5.684685,5.181818,1.221489,1.187690,1.716625,10,1
2499,4.913043,2.090571,5.109324,3.459555,3.616166,6.853220,7.057520,3.182581,3.972821,7.005107,...,9.573079,2.559916,3.376842,3.207207,2.636364,1.347539,5.438722,9.238624,1,1

In [18]:
df.describe()

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,5.475583,5.340519,5.468778,5.458627,5.473076,5.548873,5.457266,5.468048,5.528713,5.416621,...,5.562995,5.362919,5.524103,5.474418,5.584655,5.480132,5.519653,5.476411,5.608000,5.262400
std,2.698228,2.579465,2.609537,2.607290,2.626972,2.603805,2.627096,2.623441,2.616652,2.611470,...,2.579606,2.595056,2.585449,2.668297,2.625197,2.594777,2.641111,2.604372,4.499604,4.494622
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3.347826,3.116686,3.195326,3.222220,3.227570,3.271167,3.127824,3.193693,3.302447,3.178780,...,3.355452,3.117132,3.332408,3.108108,3.363636,3.277011,3.198283,3.155096,1.000000,1.000000
50%,5.304348,5.215275,5.433821,5.463687,5.506873,5.622098,5.461024,5.428311,5.519465,5.276962,...,5.573273,5.334587,5.624835,5.441441,5.636364,5.492347,5.493611,5.519897,10.000000,1.000000
75%,7.750000,7.555498,7.734081,7.676318,7.708461,7.840270,7.783798,7.781268,7.805448,7.727524,...,7.741381,7.605145,7.724659,7.801802,7.909091,7.718487,7.890083,7.691929,10.000000,10.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [19]:
#for standardization
from sklearn.preprocessing import StandardScaler
s= StandardScaler()

In [20]:
s.fit_transform(df)

array([[-0.06347464,  1.29384776, -1.33695424, ..., -0.82442719,
         0.97628121, -0.94852309],
       [-0.49862983, -0.93657649,  1.26749409, ...,  1.56489453,
        -1.02429504,  1.05427059],
       [ 0.22662883,  1.60081675, -1.29620045, ...,  0.60879423,
         0.97628121, -0.94852309],
       ...,
       [ 1.53209441,  1.60882297, -0.14697997, ..., -0.848301  ,
        -1.02429504,  1.05427059],
       [-1.65904368,  0.61630367, -1.47662988, ..., -1.44393265,
         0.97628121, -0.94852309],
       [-0.20852637, -1.26018314, -0.13777403, ...,  1.44486513,
        -1.02429504, -0.94852309]])

In [21]:
df

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
0,5.304348,8.677287,1.980645,6.042244,7.384006,8.991576,4.320976,9.375350,2.124872,3.642929,...,5.426018,6.195238,7.911834,8.666667,7.818182,6.724490,5.606317,3.329725,10,1
1,4.130435,2.925136,8.775689,1.567703,7.199281,3.895332,7.946087,1.065139,8.050021,8.438394,...,8.199418,1.156461,5.381667,6.315315,4.545455,9.777611,9.781221,9.551163,1,10
2,6.086957,9.468945,2.086972,6.541722,1.081935,8.057865,4.078048,6.833135,4.646916,1.383636,...,9.495638,7.995555,7.059447,1.909910,1.636364,1.277311,3.936139,7.061620,10,1
3,4.913043,8.983759,8.254636,8.674035,9.695641,7.078633,5.485557,5.478439,4.728454,8.563181,...,6.861347,5.051642,1.406779,3.945946,1.272727,7.937275,5.556033,4.036205,1,1
4,8.043478,9.394829,6.528309,5.575790,10.000000,4.905171,8.372333,6.647050,2.534545,2.450082,...,8.760213,6.632876,1.923780,9.873874,7.272727,5.426170,2.689372,6.355221,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,10.000000,4.553053,9.396071,6.029119,5.917629,5.996037,6.170993,6.121207,6.693025,8.112510,...,6.141786,5.402209,6.424067,9.018018,3.272727,9.993697,8.958928,3.646001,10,1
2496,7.652174,1.764607,6.122601,6.040933,1.692418,7.454637,7.673952,6.058784,4.897675,1.612887,...,7.206190,8.729275,4.530975,9.090090,8.000000,6.835234,5.029297,7.595171,10,10
2497,9.608696,9.489592,5.085305,8.731988,9.456820,3.511474,9.305997,8.680933,5.220892,7.696935,...,3.942861,1.092300,5.614284,6.423423,5.454545,4.180072,5.825637,3.267561,1,10
2498,1.000000,6.929935,1.616229,6.075270,6.157627,1.964574,5.326660,4.994048,7.675311,3.358514,...,6.425156,3.634544,2.549587,5.684685,5.181818,1.221489,1.187690,1.716625,10,1
2499,4.913043,2.090571,5.109324,3.459555,3.616166,6.853220,7.057520,3.182581,3.972821,7.005107,...,9.573079,2.559916,3.376842,3.207207,2.636364,1.347539,5.438722,9.238624,1,1

In [22]:
df.describe()

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,5.475583,5.340519,5.468778,5.458627,5.473076,5.548873,5.457266,5.468048,5.528713,5.416621,...,5.562995,5.362919,5.524103,5.474418,5.584655,5.480132,5.519653,5.476411,5.608000,5.262400
std,2.698228,2.579465,2.609537,2.607290,2.626972,2.603805,2.627096,2.623441,2.616652,2.611470,...,2.579606,2.595056,2.585449,2.668297,2.625197,2.594777,2.641111,2.604372,4.499604,4.494622
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3.347826,3.116686,3.195326,3.222220,3.227570,3.271167,3.127824,3.193693,3.302447,3.178780,...,3.355452,3.117132,3.332408,3.108108,3.363636,3.277011,3.198283,3.155096,1.000000,1.000000
50%,5.304348,5.215275,5.433821,5.463687,5.506873,5.622098,5.461024,5.428311,5.519465,5.276962,...,5.573273,5.334587,5.624835,5.441441,5.636364,5.492347,5.493611,5.519897,10.000000,1.000000
75%,7.750000,7.555498,7.734081,7.676318,7.708461,7.840270,7.783798,7.781268,7.805448,7.727524,...,7.741381,7.605145,7.724659,7.801802,7.909091,7.718487,7.890083,7.691929,10.000000,10.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000