In [54]:
#ordinal encoder, Label encoder 
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

d1={"Education":["Phd","Pg","Ug","School"],
    "Review":["Excellent","Very good","Good","poor"],
    "Result":["Yes","No","Yes","No"]}
df1=pd.DataFrame(d1)
df1

  Education     Review Result
0       Phd  Excellent    Yes
1        Pg  Very good     No
2        Ug       Good    Yes
3    School       poor     No

In [56]:
ode= OrdinalEncoder(categories=[["School","Ug","Pg","Phd"],
                                ["Good","Very good","Excellent","poor"]])

In [57]:
x=["Education","Review"]

In [58]:
df1[x]=ode.fit_transform(df1[x])

In [59]:
print(df1)

   Education  Review Result
0        3.0     2.0    Yes
1        2.0     1.0     No
2        1.0     0.0    Yes
3        0.0     3.0     No

In [60]:
#result- label output
le=LabelEncoder()
df1["Result"]=le.fit_transform(df1["Result"])
df1

   Education  Review  Result
0        3.0     2.0       1
1        2.0     1.0       0
2        1.0     0.0       1
3        0.0     3.0       0

#TargetEncoder- focus on target- then avg of output of same input - it solves problem of bulky- but it can cause data leakage- 
also called categorical encoder or mean encoder
eg
TARGET OR MEAN OR CATEGORY  ENCODER
AVERAGE OF SAME INPUTS
PROS:BULKY DATADET ISSUE IS SOLVED
CONS:DATA LEAKAGE

I/P       O/P   new O/P
CSE        0      0.5
CSE        1      0.5
ECE        1       1
ECE        1       1

same input CSE avg=(0+1)/2=0.5
similarly  ECE avg=(1+1)/2=1

In [1]:
import pandas as pd 
df=pd.read_csv("tips.csv")

In [62]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\sai\anaconda\lib\site-packages (from category_encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in c:\users\sai\anaconda\lib\site-packages (from category_encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\sai\anaconda\lib\site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\sai\anaconda\lib\site-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\sai\anaconda\lib\site-packages (from category_encoders) (1.15.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\sai\anaconda\lib\site-packages (from category_encoders) (0.14.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sai\anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sai\anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sai\anaconda\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sai\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sai\anaconda\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sai\anaconda\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\sai\anaconda\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [4]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679

In [6]:
import category_encoders as ce

In [7]:
encoder=ce.TargetEncoder(cols="sex")
encoder.fit_transform(df["sex"],df["tip"])

          sex
0    2.833651
1    3.089618
2    3.089618
3    3.089618
4    2.833651
..        ...
239  3.089618
240  2.833651
241  3.089618
242  3.089618
243  2.833651

[244 rows x 1 columns]

In [10]:
encoder1=ce.TargetEncoder(cols="smoker")
encoder1.fit_transform(df["smoker"],df["tip"])

       smoker
0    2.991854
1    2.991854
2    2.991854
3    2.991854
4    2.991854
..        ...
239  2.991854
240  3.008703
241  3.008703
242  2.991854
243  2.991854

[244 rows x 1 columns]